 # Generated by Django 3.2.20 on 2023-08-29 16:18

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20230822_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
