# Generated by Django 3.2.20 on 2023-08-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'default_related_name': 'stores'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={},
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='my_app.Author'),
        ),
        migrations.AlterField(
            model_name='store',
            name='books',
            field=models.ManyToManyField(to='my_app.Book'),
        ),
    ]
